/** The published CP-102 schema surface. Migration SQL is the source of truth;
 * this manifest is intentionally only a reviewable inventory used by tests and
 * diagnostics. Keep names stable after a migration is released. */
export const CONTROL_PLANE_SCHEMA_VERSION = 4;

export const controlPlaneSchemaManifest = {
  tables: [
    "control_projects",
    "agent_profiles",
    "managed_agents",
    "work_sessions",
    "task_dependencies",
    "decision_clusters",
    "decision_requests",
    "decision_cluster_requests",
    "decision_request_impacts",
    "decisions",
    "decision_resolutions",
    "assumptions",
    "human_inputs",
    "agent_messages",
    "agent_message_recipients",
    "investigations",
    "investigation_subscribers",
    "findings",
    "investigation_results",
    "resource_claims",
    "review_requests",
    "review_findings",
    "outbox",
    "processed_events",
  ],
  indexes: [
    "work_sessions_project_status",
    "task_dependencies_project",
    "decision_requests_project_status",
    "decision_cluster_requests_request",
    "decision_request_impacts_request",
    "decision_resolutions_decision",
    "decisions_one_successor",
    "assumptions_project_status",
    "human_inputs_project_status",
    "agent_messages_project_status",
    "agent_message_recipients_recipient_status",
    "investigations_project_status",
    "investigation_subscribers_subscriber",
    "findings_project_type_fingerprint",
    "investigation_results_finding",
    "resource_claims_project_status_expiry",
    "review_requests_project_status",
    "review_findings_review",
    "outbox_delivery",
  ],
  triggers: [
    "decisions_immutable_content",
    "resource_claims_exclusive_insert",
    "resource_claims_exclusive_update",
    "resource_claims_shared_insert",
    "resource_claims_shared_update",
  ],
} as const;
